# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manille.ui'
#
# Created: Tue Sep  8 20:41:38 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_manille(object):
    def setupUi(self, manille):
        manille.setObjectName(_fromUtf8("manille"))
        manille.resize(800, 600)
        manille.setMinimumSize(QtCore.QSize(800, 600))
        manille.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(manille)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 440, 704, 138))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.card0 = QtGui.QPushButton(self.layoutWidget)
        self.card0.setMaximumSize(QtCore.QSize(80, 120))
        self.card0.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("GreyWyvern/cardset/01c.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card0.setIcon(icon)
        self.card0.setIconSize(QtCore.QSize(80, 120))
        self.card0.setObjectName(_fromUtf8("card0"))
        self.horizontalLayout.addWidget(self.card0)
        self.card1 = QtGui.QPushButton(self.layoutWidget)
        self.card1.setMaximumSize(QtCore.QSize(80, 120))
        self.card1.setText(_fromUtf8(""))
        self.card1.setIcon(icon)
        self.card1.setIconSize(QtCore.QSize(80, 120))
        self.card1.setObjectName(_fromUtf8("card1"))
        self.horizontalLayout.addWidget(self.card1)
        self.card2 = QtGui.QPushButton(self.layoutWidget)
        self.card2.setMaximumSize(QtCore.QSize(80, 120))
        self.card2.setText(_fromUtf8(""))
        self.card2.setIcon(icon)
        self.card2.setIconSize(QtCore.QSize(80, 120))
        self.card2.setObjectName(_fromUtf8("card2"))
        self.horizontalLayout.addWidget(self.card2)
        self.card3 = QtGui.QPushButton(self.layoutWidget)
        self.card3.setMaximumSize(QtCore.QSize(80, 120))
        self.card3.setText(_fromUtf8(""))
        self.card3.setIcon(icon)
        self.card3.setIconSize(QtCore.QSize(80, 120))
        self.card3.setObjectName(_fromUtf8("card3"))
        self.horizontalLayout.addWidget(self.card3)
        self.card4 = QtGui.QPushButton(self.layoutWidget)
        self.card4.setMaximumSize(QtCore.QSize(80, 120))
        self.card4.setText(_fromUtf8(""))
        self.card4.setIcon(icon)
        self.card4.setIconSize(QtCore.QSize(80, 120))
        self.card4.setObjectName(_fromUtf8("card4"))
        self.horizontalLayout.addWidget(self.card4)
        self.card5 = QtGui.QPushButton(self.layoutWidget)
        self.card5.setMaximumSize(QtCore.QSize(80, 120))
        self.card5.setText(_fromUtf8(""))
        self.card5.setIcon(icon)
        self.card5.setIconSize(QtCore.QSize(80, 120))
        self.card5.setObjectName(_fromUtf8("card5"))
        self.horizontalLayout.addWidget(self.card5)
        self.card6 = QtGui.QPushButton(self.layoutWidget)
        self.card6.setMaximumSize(QtCore.QSize(80, 120))
        self.card6.setText(_fromUtf8(""))
        self.card6.setIcon(icon)
        self.card6.setIconSize(QtCore.QSize(80, 120))
        self.card6.setObjectName(_fromUtf8("card6"))
        self.horizontalLayout.addWidget(self.card6)
        self.card7 = QtGui.QPushButton(self.layoutWidget)
        self.card7.setMaximumSize(QtCore.QSize(80, 120))
        self.card7.setText(_fromUtf8(""))
        self.card7.setIcon(icon)
        self.card7.setIconSize(QtCore.QSize(80, 120))
        self.card7.setObjectName(_fromUtf8("card7"))
        self.horizontalLayout.addWidget(self.card7)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(290, 0, 290, 440))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.T0 = QtGui.QLabel(self.layoutWidget1)
        self.T0.setMinimumSize(QtCore.QSize(90, 140))
        self.T0.setText(_fromUtf8(""))
        self.T0.setPixmap(QtGui.QPixmap(_fromUtf8("GreyWyvern/cardset/bottom02.gif")))
        self.T0.setObjectName(_fromUtf8("T0"))
        self.gridLayout.addWidget(self.T0, 1, 1, 1, 1)
        self.T1 = QtGui.QLabel(self.layoutWidget1)
        self.T1.setMinimumSize(QtCore.QSize(90, 140))
        self.T1.setText(_fromUtf8(""))
        self.T1.setPixmap(QtGui.QPixmap(_fromUtf8("GreyWyvern/cardset/bottom02.gif")))
        self.T1.setObjectName(_fromUtf8("T1"))
        self.gridLayout.addWidget(self.T1, 0, 2, 1, 1)
        self.T2 = QtGui.QLabel(self.layoutWidget1)
        self.T2.setMinimumSize(QtCore.QSize(90, 140))
        self.T2.setText(_fromUtf8(""))
        self.T2.setPixmap(QtGui.QPixmap(_fromUtf8("GreyWyvern/cardset/bottom02.gif")))
        self.T2.setObjectName(_fromUtf8("T2"))
        self.gridLayout.addWidget(self.T2, 1, 3, 1, 1)
        self.T3 = QtGui.QLabel(self.layoutWidget1)
        self.T3.setMinimumSize(QtCore.QSize(90, 140))
        self.T3.setText(_fromUtf8(""))
        self.T3.setPixmap(QtGui.QPixmap(_fromUtf8("GreyWyvern/cardset/bottom02.gif")))
        self.T3.setObjectName(_fromUtf8("T3"))
        self.gridLayout.addWidget(self.T3, 2, 2, 1, 1)
        self.next = QtGui.QPushButton(self.layoutWidget1)
        self.next.setObjectName(_fromUtf8("next"))
        self.gridLayout.addWidget(self.next, 1, 2, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 0, 92, 167))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.trump_label = QtGui.QLabel(self.layoutWidget2)
        self.trump_label.setObjectName(_fromUtf8("trump_label"))
        self.verticalLayout.addWidget(self.trump_label)
        self.trump_disp = QtGui.QLabel(self.layoutWidget2)
        self.trump_disp.setMinimumSize(QtCore.QSize(90, 140))
        self.trump_disp.setText(_fromUtf8(""))
        self.trump_disp.setPixmap(QtGui.QPixmap(_fromUtf8("GreyWyvern/cardset/bottom02.gif")))
        self.trump_disp.setObjectName(_fromUtf8("trump_disp"))
        self.verticalLayout.addWidget(self.trump_disp)
        manille.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(manille)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        manille.setStatusBar(self.statusBar)

        self.retranslateUi(manille)
        QtCore.QMetaObject.connectSlotsByName(manille)

    def retranslateUi(self, manille):
        manille.setWindowTitle(_translate("manille", "PyManille!", None))
        self.next.setText(_translate("manille", "OK", None))
        self.trump_label.setText(_translate("manille", "Trump:", None))

